const zones=[{id:'lobby',name:'Lobby',sub:'Main entrance and reception',temp:'21.2°C',setpoint:'21.0°C',occupancy:'42%',mode:'Auto',status:'normal'},{id:'office',name:'Office A',sub:'Open office area',temp:'22.1°C',setpoint:'22.0°C',occupancy:'78%',mode:'Auto',status:'normal'},{id:'lab',name:'Lab 02',sub:'Lab and research space',temp:'24.8°C',setpoint:'22.0°C',occupancy:'65%',mode:'Cooling',status:'warning'},{id:'server',name:'Server Room',sub:'IT infrastructure',temp:'18.6°C',setpoint:'18.0°C',occupancy:'24%',mode:'Precision',status:'normal'}];
let selected='server';let filter='all';let alerts=[{title:'Lab 02: temperature above setpoint',meta:'Current 24.8°C / Setpoint 22.0°C · 14:20',kind:'warning'},{title:'Office A: temperature back to normal',meta:'Current 21.9°C / Setpoint 22.0°C · 12:37',kind:'resolved'}];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function renderZones(){const visible=filter==='all'?zones:zones.filter(z=>filter==='attention'?z.status==='warning':z.status==='normal');$('#zoneSummary').textContent=`${visible.length} zone${visible.length===1?'':'s'} shown`;$('#zoneTable').innerHTML=`<div class="zone-head"><span>Zone</span><span>Temp</span><span>Setpoint</span><span>Occupancy</span><span>Mode</span></div>`+visible.map(z=>`<div class="zone-row ${z.id===selected?'selected':''}" data-zone="${z.id}" role="listitem" tabindex="0"><div><div class="zone-name"><span class="dot ${z.status==='warning'?'warning-dot':'normal-dot'}"></span>${z.name}</div><div class="zone-sub">${z.sub}</div></div><span class="zone-val">${z.temp}</span><span class="zone-val">${z.setpoint}</span><span class="zone-val">${z.occupancy}</span><span class="status-text ${z.status}">${z.mode}</span></div>`).join('');$$('.zone-row').forEach(el=>{el.addEventListener('click',()=>selectZone(el.dataset.zone));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectZone(el.dataset.zone)}})});}
function selectZone(id){selected=id;$$('.zone').forEach(el=>el.classList.toggle('selected',el.dataset.zone===id));renderZones();const z=zones.find(x=>x.id===id);if(z)toast(`${z.name} selected · ${z.temp} · ${z.mode}`)}
function renderAlerts(){ $('#alertsList').innerHTML=alerts.map((a,i)=>`<div class="alert ${a.kind}"><i class="alert-marker"></i><div><div class="alert-title">${a.title}</div><div class="alert-meta">${a.meta}</div></div></div>`).join('');$('#alertCount').textContent=alerts.filter(a=>a.kind==='warning').length;}
function refresh(){const now=new Date();$('#lastUpdated').textContent='just now';$('#clock').textContent=now.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})+'  '+now.toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit',hour12:false});toast('Telemetry refreshed');}
$$('.zone').forEach(el=>el.addEventListener('click',()=>selectZone(el.dataset.zone)));$('#refreshBtn').addEventListener('click',refresh);$('#clearAlerts').addEventListener('click',()=>{alerts=alerts.filter(a=>a.kind!=='resolved');renderAlerts();toast('Resolved alerts cleared')});$('#trendBtn').addEventListener('click',()=>toast('Trend view is already shown for the last 24 hours'));$('#dataViewBtn').addEventListener('click',()=>toast('Data view: semantic zone telemetry is active'));$('#activityBtn').addEventListener('click',()=>toast('Activity log opened'));$('#helpBtn').addEventListener('click',()=>toast('Select a zone or alert to inspect its current state'));$('.avatar').addEventListener('click',()=>toast('Signed in as Jordan Smith'));
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const label=btn.textContent.trim();if(label.startsWith('Overview'))toast('Overview selected');else toast(`${label.replace(/\d/g,'').trim()} is available from this console`)}));
renderZones();renderAlerts();setInterval(()=>$('#lastUpdated').textContent='a few seconds ago',10000);
