"""
FastAPI REST endpoints for the Digital Twin HVAC Optimizer.

All endpoints operate against the shared `SimulationCoordinator` instance
and return Pydantic-validated responses. The /api/stream endpoint mounts
the async SSE generator from `src.api.sse`.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field, field_validator

from src.api.coordinator import SimulationCoordinator
from src.api.sse import telemetry_event_stream
from src.config import WeatherPreset

logger = logging.getLogger("hvac.api.routes")

router = APIRouter(prefix="/api", tags=["api"])


# ---------------------------------------------------------------------------
# Pydantic request / response models (with strict zero-hallucination typing)
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    """Body for POST /api/chat."""
    model_config = ConfigDict(extra="forbid")

    message: str = Field(..., min_length=1, description="Occupant natural-language message")
    history: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Short-term dialogue history for multi-turn context (role/content)"
    )
    environment_id: str = Field(default="corporate", description="Contextual 3D environment ID")


class ChatResponse(BaseModel):
    """Body for POST /api/chat response."""
    model_config = ConfigDict(extra="forbid")

    translation: Dict[str, Any] = Field(..., description="Raw SemanticTranslationResult as dict")
    applied: bool = Field(..., description="Whether constraints were injected into the simulator")
    is_applicable: bool = Field(..., description="Whether the message was an environmental complaint")
    response_text: str = Field(..., description="Conversational reply generated by the NLP engine")


class ZoneState(BaseModel):
    """Single zone state."""
    model_config = ConfigDict(extra="forbid")

    zone_id: str
    temperature_c: float
    target_setpoint_c: float
    humidity_pct: float
    occupancy_count: int
    hvac_power_kw: float
    comfort_violation_c: float
    active_nlp_offset_c: float


class ZonesResponse(BaseModel):
    """Body for GET /api/zones."""
    model_config = ConfigDict(extra="forbid")

    zones: List[str]
    states: Dict[str, ZoneState]


class MetricsResponse(BaseModel):
    """Body for GET /api/metrics."""
    model_config = ConfigDict(extra="forbid")

    step: int
    timestamp_sim_hour: float
    outdoor_temp_c: float
    outdoor_humidity_pct: float
    solar_irradiance_w_m2: float
    electricity_price_usd_kwh: float
    baseline_power_kw: float
    rl_power_kw: float
    power_saved_kw: float
    instantaneous_savings_pct: float
    cumulative_baseline_energy_kwh: float
    cumulative_rl_energy_kwh: float
    cumulative_savings_pct: float
    cumulative_cost_saved_usd: float
    baseline_comfort_violation_total: float
    rl_comfort_violation_total: float
    history: List[Dict[str, Any]] = Field(default_factory=list)


class SimulationControlRequest(BaseModel):
    """Body for POST /api/simulation/control."""
    model_config = ConfigDict(extra="forbid")

    action: str = Field(..., description="start|pause|step|reset|set_speed|set_weather_preset")
    speed: Optional[float] = Field(default=None, ge=0.0, le=50.0)
    steps: Optional[int] = Field(default=None, ge=1, le=10000)
    preset: Optional[str] = Field(default=None)

    @field_validator("action")
    @classmethod
    def validate_action(cls, v: str) -> str:
        allowed = {"start", "pause", "step", "reset", "set_speed", "set_weather_preset"}
        if v not in allowed:
            raise ValueError(f"action must be one of {sorted(allowed)}, got '{v}'")
        return v


class SimulationControlResponse(BaseModel):
    """Body for POST /api/simulation/control response."""
    model_config = ConfigDict(extra="forbid")

    status: str
    action: str
    running: bool
    speed: float
    extra: Dict[str, Any] = Field(default_factory=dict)


class StatusResponse(BaseModel):
    """Body for GET /api/status."""
    model_config = ConfigDict(extra="forbid")

    status: str
    running: bool
    speed: float
    initialized: bool
    subscribers: int
    sim_step: int
    sim_time_minutes: float
    llm_engine_active: bool
    version: str = "1.0.0"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _coordinator(request: Request) -> SimulationCoordinator:
    coord: Optional[SimulationCoordinator] = getattr(request.app.state, "coordinator", None)
    if coord is None:
        raise HTTPException(status_code=503, detail="Coordinator not attached")
    return coord


# ---------------------------------------------------------------------------
# Endpoint definitions
# ---------------------------------------------------------------------------


@router.post("/chat")
async def chat_endpoint(request: Request, body: ChatRequest) -> StreamingResponse:
    """Translates a natural-language message and streams the response text, then injects constraints.
    Enforces 100% local inference via Ollama on Raspberry Pi. Zero cloud fallback."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio
    import os
    import json
    import re
    
    async def generate_chat_events():
        # Local Ollama is strictly required for AI inference
        ollama_url = os.environ.get("OLLAMA_URL")
        if not ollama_url:
            err_msg = "Local AI configuration error: OLLAMA_URL is not set. DigitalBMS requires local Ollama inference."
            logger.error(err_msg)
            yield f"data: {json.dumps({'chunk': f'⚠️ {err_msg}'})}\n\n"
            yield f"data: {json.dumps({'error': err_msg, 'status': 503, 'applied': False, 'is_applicable': False})}\n\n"
            return

        from src.nlp.local_translator import LocalTranslator, build_full_prompt
        ollama_model = os.environ.get("OLLAMA_MODEL", "qwen3:1.7b")
        ollama_timeout = float(os.environ.get("OLLAMA_TIMEOUT_SECONDS", "180.0"))
        
        local_t = LocalTranslator(
            backend_type="ollama", 
            ollama_url=ollama_url, 
            model_name=ollama_model,
            timeout=ollama_timeout,
            fallback_to_mock=False,
        )
        
        prompt = build_full_prompt(body.message, environment_id=body.environment_id)
        full_text = ""
        is_json_part = False
        yielded_len = 0
        has_yielded_chunk = False
        
        # Stream the conversational response from local Ollama
        try:
            for chunk in local_t.backend.generate_stream(prompt=prompt, grammar=None):
                full_text += chunk
                
                if not is_json_part:
                    # When a boundary matching r"(\n\s*JSON\s*:?|\n\s*\{|\s*\{)" is reached, mark is_json_part = True and do not emit the delimiter.
                    boundary_match = re.search(r"(\n\s*JSON\s*:?|\n\s*\{|\s*\{)", full_text)
                    if boundary_match:
                        is_json_part = True
                        boundary_start = boundary_match.start()
                        unyielded = full_text[yielded_len:boundary_start]
                    else:
                        # Lookahead buffer: do not yield trailing characters that match prefixes of "\nJSON:" or "\n{" or "{" until boundary resolution.
                        lookahead_len = 0
                        for p in ("\nJSON:", "\nJSON", "\nJSO", "\nJS", "\nJ", "\n", "JSON:", "JSON", "JSO", "JS", "J", "\n{", "{"):
                            if full_text.endswith(p):
                                lookahead_len = max(lookahead_len, len(p))
                        m_la = re.search(r"(\n\s*(?:J(?:S(?:O(?:N:?)?)?)?|\{)?|\s+J(?:S(?:O(?:N:?)?)?)?|\{)$", full_text)
                        if m_la:
                            lookahead_len = max(lookahead_len, len(m_la.group(0)))

                        safe_end = len(full_text) - lookahead_len
                        if safe_end > yielded_len:
                            unyielded = full_text[yielded_len:safe_end]
                        else:
                            unyielded = ""

                    if unyielded:
                        # Buffer the first few characters if it looks like it might be typing "Response:"
                        if yielded_len == 0 and len(full_text.lstrip()) < 10 and "Response:".startswith(full_text.lstrip()):
                            continue
                            
                        # Strip "Response:" if it's at the start
                        if yielded_len == 0:
                            resp_pfx = re.match(r"^\s*Response:\s*", unyielded)
                            if resp_pfx:
                                unyielded = unyielded[resp_pfx.end():]
                                
                        # Strip any accidental trailing "JSON", "JSON:", or "Response:" from conversational unyielded text
                        unyielded = re.sub(r'(?:\s*(?:JSON\s*:?|Response:))+\s*$', '', unyielded)
                        
                        if unyielded:
                            yield f"data: {json.dumps({'chunk': unyielded})}\n\n"
                            has_yielded_chunk = True
                            
                    if is_json_part:
                        yielded_len = boundary_match.end()
                    else:
                        yielded_len = safe_end
                        
                await asyncio.sleep(0)

            # Ensure any remaining conversational tokens are flushed if stream ended before boundary
            if not is_json_part and len(full_text) > yielded_len:
                boundary_match = re.search(r"(\n\s*JSON\s*:?|\n\s*\{|\s*\{)", full_text)
                boundary_pos = boundary_match.start() if boundary_match else len(full_text)
                if boundary_pos > yielded_len:
                    unyielded = full_text[yielded_len:boundary_pos]
                    if yielded_len == 0:
                        resp_pfx = re.match(r"^\s*Response:\s*", unyielded)
                        if resp_pfx:
                            unyielded = unyielded[resp_pfx.end():]
                    unyielded = re.sub(r'(?:\s*(?:JSON\s*:?|Response:))+\s*$', '', unyielded)
                    if unyielded:
                        yield f"data: {json.dumps({'chunk': unyielded})}\n\n"
                        has_yielded_chunk = True
                yielded_len = len(full_text)
        except Exception as e:
            err_msg = f"Local AI error: Unable to reach Ollama at {ollama_url} ({e}). Please ensure Raspberry Pi is online and Ollama is running."
            logger.error(err_msg)
            yield f"data: {json.dumps({'chunk': f'⚠️ {err_msg}'})}\n\n"
            yield f"data: {json.dumps({'error': err_msg, 'status': 503, 'applied': False, 'is_applicable': False})}\n\n"
            return
        
        # Now parse the full_text for JSON
        res = local_t.parse_raw_output(full_text, original_text=body.message)
        
        # Create a mock TranslationResult to map
        from src.nlp.local_translator import TranslationResult
        local_res = TranslationResult(
            success=True,
            event=res,
            error_message=None,
            raw_response=full_text,
            backend_used="ollama",
            execution_time_ms=0.0
        )
        
        # Map it using same logic from translator.py
        from src.nlp.schemas import ComfortEvent as SemanticComfortEvent
        from src.nlp.schemas import ComfortIntent, SuspectedCause, SeverityLevel, SemanticTranslationResult
        from src.nlp.schemas import ALLOWED_ZONE_IDS, ZONE_ALIAS_MAP
        
        sensation_map = {
            "too_hot": ComfortIntent.TOO_WARM,
            "hot": ComfortIntent.TOO_WARM,
            "warm": ComfortIntent.TOO_WARM,
            "boiling": ComfortIntent.TOO_WARM,
            "overheating": ComfortIntent.TOO_WARM,
            "cold": ComfortIntent.TOO_COLD,
            "freezing": ComfortIntent.TOO_COLD,
            "chilly": ComfortIntent.TOO_COLD,
            "humid": ComfortIntent.TOO_HUMID,
            "dry": ComfortIntent.TOO_DRY,
            "comfortable": ComfortIntent.COMFORTABLE,
            "too_warm": ComfortIntent.TOO_WARM,
            "too_cold": ComfortIntent.TOO_COLD,
            "too_humid": ComfortIntent.TOO_HUMID,
            "too_dry": ComfortIntent.TOO_DRY,
            "stuffy": ComfortIntent.STUFFY,
            "drafty": ComfortIntent.DRAFTY,
            "glare": ComfortIntent.UNKNOWN,
            "other": ComfortIntent.UNKNOWN,
        }
        raw_sensation = str(getattr(res, "sensation", "") or "").lower().strip()
        intent = sensation_map.get(raw_sensation, ComfortIntent.UNKNOWN)
        
        # Substring matching fallback if UNKNOWN
        if intent == ComfortIntent.UNKNOWN:
            sens_lower = raw_sensation
            msg_lower = body.message.lower()
            for key, mapped_intent in sensation_map.items():
                if mapped_intent == ComfortIntent.UNKNOWN:
                    continue
                key_clean = key.replace("_", " ")
                if key in sens_lower or key_clean in sens_lower or key in msg_lower or key_clean in msg_lower:
                    intent = mapped_intent
                    break

        raw_zone = res.location or "open_office"
        norm_zone = str(raw_zone).strip().lower().replace("-", "_").replace(" ", "_")
        zone_id = ZONE_ALIAS_MAP.get(norm_zone, norm_zone)
        if zone_id not in ALLOWED_ZONE_IDS:
            zone_id = "open_office"

        severity = SeverityLevel.MEDIUM
        if res.intensity >= 4:
            severity = SeverityLevel.HIGH
        elif res.intensity <= 2:
            severity = SeverityLevel.LOW

        mapped_event = SemanticComfortEvent(
            event_id=res.event_id,
            zone_id=zone_id,
            intent=intent,
            suspected_cause=SuspectedCause.UNSPECIFIED,
            severity=severity,
            confidence=res.confidence,
            duration_minutes=60,
            source="Ollama",
            reasoning=f"Mapped from local backend. Sensation: {res.sensation}"
        )
        
        # Get the response text part from full_text
        resp_match = re.search(r"Response:\s*(.*?)(?:\n\s*JSON\s*:?|\n\s*\{|\s*\{|$)", full_text, re.DOTALL)
        if resp_match and resp_match.group(1).strip():
            friendly_response = resp_match.group(1).strip()
            # Clean any trailing "JSON" or "JSON:" from friendly_response
            friendly_response = re.sub(r'(?:\s*JSON\s*:?)+$', '', friendly_response).strip()
        else:
            friendly_response = ""

        zone_display = zone_id.replace("_", " ").title()
        if not friendly_response:
            if intent == ComfortIntent.TOO_WARM:
                friendly_response = f"Understood. Increasing cooling for the {zone_display}."
            elif intent == ComfortIntent.TOO_COLD:
                friendly_response = f"Got it. Increasing heating for the {zone_display}."
            elif intent in (ComfortIntent.TOO_HUMID, ComfortIntent.STUFFY):
                friendly_response = f"Understood. Increasing ventilation for the {zone_display}."
            elif intent == ComfortIntent.DRAFTY:
                friendly_response = f"Adjusting airflow to reduce drafts in the {zone_display}."
            elif intent == ComfortIntent.TOO_DRY:
                friendly_response = f"Understood. Increasing humidity in the {zone_display}."
            elif intent == ComfortIntent.COMFORTABLE:
                friendly_response = f"Great to hear! Maintaining current comfort settings in the {zone_display}."
            else:
                friendly_response = f"Acknowledged. Monitoring comfort parameters in the {zone_display}."

        # Conversational consistency safeguard
        if intent == ComfortIntent.TOO_WARM and re.search(r"\b(increasing\s+(the\s+)?heat|heating|turning\s+up\s+(the\s+)?heat)\b", friendly_response, re.I):
            friendly_response = f"Understood, increasing cooling for the {zone_display} right away."
        elif intent == ComfortIntent.TOO_COLD and re.search(r"\b(increasing\s+cooling|cooling|turning\s+up\s+(the\s+)?ac)\b", friendly_response, re.I):
            friendly_response = f"Got it, increasing heating for the {zone_display} right away."

        # If no conversational chunk was yielded during streaming, yield the dynamic friendly response
        if (yielded_len == 0 or not has_yielded_chunk) and friendly_response:
            yield f"data: {json.dumps({'chunk': friendly_response})}\n\n"
        
        final_translation = SemanticTranslationResult(
            raw_query=body.message,
            is_applicable=(res.domain.lower() == "thermal"),
            response_text=friendly_response,
            events=[mapped_event],
            timestamp=0.0
        )
        
        # Inject into simulator
        applied = False
        if final_translation.is_applicable and final_translation.events:
            for c in final_translation.events:
                await asyncio.to_thread(
                    coord.runner.inject_nlp_constraint,
                    c
                )
            applied = True
        
        # Yield the final payload
        yield f"data: {json.dumps({'applied': bool(applied), 'is_applicable': final_translation.is_applicable, 'translation': final_translation.model_dump()})}\n\n"

    sse_generator = generate_chat_events
    return StreamingResponse(generate_chat_events(), media_type="text/event-stream")


@router.get("/zones", response_model=ZonesResponse)
async def zones_endpoint(request: Request) -> ZonesResponse:
    """Returns the current state of all zones."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    zone_states = await asyncio.to_thread(coord.get_zone_states)
    zone_ids = await asyncio.to_thread(coord.get_zone_ids)

    states: Dict[str, ZoneState] = {}
    for zid, st in zone_states.items():
        try:
            states[zid] = ZoneState(**st)
        except Exception:
            # Defensive normalization if upstream sends malformed data.
            states[zid] = ZoneState(
                zone_id=zid,
                temperature_c=float(st.get("temperature_c", 22.0)),
                target_setpoint_c=float(st.get("target_setpoint_c", 22.0)),
                humidity_pct=float(st.get("humidity_pct", 50.0)),
                occupancy_count=int(st.get("occupancy_count", 0)),
                hvac_power_kw=float(st.get("hvac_power_kw", 0.0)),
                comfort_violation_c=float(st.get("comfort_violation_c", 0.0)),
                active_nlp_offset_c=float(st.get("active_nlp_offset_c", 0.0)),
            )

    return ZonesResponse(zones=zone_ids, states=states)


@router.get("/metrics", response_model=MetricsResponse)
async def metrics_endpoint(request: Request, limit: int = 100) -> MetricsResponse:
    """Returns the latest metrics snapshot plus a short history window."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    snap = await asyncio.to_thread(coord.get_metrics_snapshot)
    history_models = await asyncio.to_thread(coord.get_telemetry_history, limit)
    history_dicts = [t.model_dump() for t in history_models]

    if not snap:
        raise HTTPException(status_code=503, detail="No telemetry available yet")

    return MetricsResponse(
        step=int(snap.get("step", 0)),
        timestamp_sim_hour=float(snap.get("timestamp_sim_hour", 0.0)),
        outdoor_temp_c=float(snap.get("outdoor_temp_c", 0.0)),
        outdoor_humidity_pct=float(snap.get("outdoor_humidity_pct", 0.0)),
        solar_irradiance_w_m2=float(snap.get("solar_irradiance_w_m2", 0.0)),
        electricity_price_usd_kwh=float(snap.get("electricity_price_usd_kwh", 0.0)),
        baseline_power_kw=float(snap.get("baseline_power_kw", 0.0)),
        rl_power_kw=float(snap.get("rl_power_kw", 0.0)),
        power_saved_kw=float(snap.get("power_saved_kw", 0.0)),
        instantaneous_savings_pct=float(snap.get("instantaneous_savings_pct", 0.0)),
        cumulative_baseline_energy_kwh=float(snap.get("cumulative_baseline_energy_kwh", 0.0)),
        cumulative_rl_energy_kwh=float(snap.get("cumulative_rl_energy_kwh", 0.0)),
        cumulative_savings_pct=float(snap.get("cumulative_savings_pct", 0.0)),
        cumulative_cost_saved_usd=float(snap.get("cumulative_cost_saved_usd", 0.0)),
        baseline_comfort_violation_total=float(snap.get("baseline_comfort_violation_total", 0.0)),
        rl_comfort_violation_total=float(snap.get("rl_comfort_violation_total", 0.0)),
        history=history_dicts,
    )


@router.post("/simulation/control", response_model=SimulationControlResponse)
async def simulation_control_endpoint(
    request: Request, body: SimulationControlRequest
) -> SimulationControlResponse:
    """Handles start/pause/step/reset/set_speed/set_weather_preset commands."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    action = body.action
    extra: Dict[str, Any] = {}

    if action == "start":
        if body.speed is not None:
            await asyncio.to_thread(coord.set_speed, body.speed)
        await asyncio.to_thread(coord.start)
    elif action == "pause":
        await asyncio.to_thread(coord.pause)
    elif action == "reset":
        await asyncio.to_thread(coord.reset)
    elif action == "step":
        steps = int(body.steps or 1)
        latest = await asyncio.to_thread(coord.step, steps)
        if latest is not None:
            extra["step_executed"] = int(latest.step)
    elif action == "set_speed":
        if body.speed is None:
            raise HTTPException(status_code=422, detail="speed is required for set_speed")
        new_speed = await asyncio.to_thread(coord.set_speed, body.speed)
        extra["new_speed"] = float(new_speed)
    elif action == "set_weather_preset":
        if body.preset is None:
            raise HTTPException(status_code=422, detail="preset is required for set_weather_preset")
        try:
            preset_enum = WeatherPreset(body.preset)
        except ValueError as exc:
            raise HTTPException(
                status_code=422,
                detail=f"unknown preset '{body.preset}'",
            ) from exc
        # Apply preset: simplest path is to swap the underlying generator's preset.
        await asyncio.to_thread(_apply_preset, coord, preset_enum)
        extra["preset"] = preset_enum.value

    return SimulationControlResponse(
        status="success",
        action=action,
        running=coord.is_running(),
        speed=coord.get_speed(),
        extra=extra,
    )


def _apply_preset(coord: SimulationCoordinator, preset: WeatherPreset) -> None:
    """Re-initializes the runner's weather generator with a new preset."""
    runner = coord.runner
    runner.env.weather_gen.reset(preset=preset)
    runner.weather_preset = preset
    # The runner's own weather_preset is informational; the env's weather_gen drives everything.


@router.get("/status", response_model=StatusResponse)
async def status_endpoint(request: Request) -> StatusResponse:
    """Returns current system status (health, running flag, sim tick, etc.)."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    sim_minutes = await asyncio.to_thread(coord.get_current_sim_time_minutes)
    return StatusResponse(
        status="healthy",
        running=coord.is_running(),
        speed=coord.get_speed(),
        initialized=coord.is_initialized(),
        subscribers=coord.get_subscriber_count(),
        sim_step=int(sim_minutes / 5.0),
        sim_time_minutes=float(sim_minutes),
        llm_engine_active=bool(getattr(coord, "_llm_engine_active", False)),
    )


@router.get("/stream")
async def stream_endpoint(request: Request) -> StreamingResponse:
    """Server-Sent Events telemetry stream."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    generator = telemetry_event_stream(coord)
    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # disable nginx buffering
            "Content-Type": "text/event-stream",
        },
    )


__all__ = [
    "router",
    "ChatRequest",
    "ChatResponse",
    "ZoneState",
    "ZonesResponse",
    "MetricsResponse",
    "SimulationControlRequest",
    "SimulationControlResponse",
    "StatusResponse",
]
