"""
FastAPI REST endpoints for the Digital Twin HVAC Optimizer.

All endpoints operate against the shared `SimulationCoordinator` instance
and return Pydantic-validated responses. The /api/stream endpoint mounts
the async SSE generator from `src.api.sse`.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Body, HTTPException, Request
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, ConfigDict, Field, field_validator

from src.api.coordinator import SimulationCoordinator
from src.api.sse import telemetry_event_stream
from src.config import WeatherPreset

logger = logging.getLogger("hvac.api.routes")

router = APIRouter(prefix="/api", tags=["api"])


# ---------------------------------------------------------------------------
# Pydantic request / response models (with strict zero-hallucination typing)
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    """Body for POST /api/chat."""
    model_config = ConfigDict(extra="forbid")

    message: str = Field(..., min_length=1, description="Occupant natural-language message")
    history: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Short-term dialogue history for multi-turn context (role/content)"
    )


class ChatResponse(BaseModel):
    """Body for POST /api/chat response."""
    model_config = ConfigDict(extra="forbid")

    translation: Dict[str, Any] = Field(..., description="Raw SemanticTranslationResult as dict")
    applied: bool = Field(..., description="Whether constraints were injected into the simulator")
    is_applicable: bool = Field(..., description="Whether the message was an environmental complaint")
    response_text: str = Field(..., description="Conversational reply generated by the NLP engine")


class ZoneState(BaseModel):
    """Single zone state."""
    model_config = ConfigDict(extra="forbid")

    zone_id: str
    temperature_c: float
    target_setpoint_c: float
    humidity_pct: float
    occupancy_count: int
    hvac_power_kw: float
    comfort_violation_c: float
    active_nlp_offset_c: float


class ZonesResponse(BaseModel):
    """Body for GET /api/zones."""
    model_config = ConfigDict(extra="forbid")

    zones: List[str]
    states: Dict[str, ZoneState]


class MetricsResponse(BaseModel):
    """Body for GET /api/metrics."""
    model_config = ConfigDict(extra="forbid")

    step: int
    timestamp_sim_hour: float
    outdoor_temp_c: float
    outdoor_humidity_pct: float
    solar_irradiance_w_m2: float
    electricity_price_usd_kwh: float
    baseline_power_kw: float
    rl_power_kw: float
    power_saved_kw: float
    instantaneous_savings_pct: float
    cumulative_baseline_energy_kwh: float
    cumulative_rl_energy_kwh: float
    cumulative_savings_pct: float
    cumulative_cost_saved_usd: float
    baseline_comfort_violation_total: float
    rl_comfort_violation_total: float
    history: List[Dict[str, Any]] = Field(default_factory=list)


class SimulationControlRequest(BaseModel):
    """Body for POST /api/simulation/control."""
    model_config = ConfigDict(extra="forbid")

    action: str = Field(..., description="start|pause|step|reset|set_speed|set_weather_preset")
    speed: Optional[float] = Field(default=None, ge=0.0, le=50.0)
    steps: Optional[int] = Field(default=None, ge=1, le=10000)
    preset: Optional[str] = Field(default=None)

    @field_validator("action")
    @classmethod
    def validate_action(cls, v: str) -> str:
        allowed = {"start", "pause", "step", "reset", "set_speed", "set_weather_preset"}
        if v not in allowed:
            raise ValueError(f"action must be one of {sorted(allowed)}, got '{v}'")
        return v


class SimulationControlResponse(BaseModel):
    """Body for POST /api/simulation/control response."""
    model_config = ConfigDict(extra="forbid")

    status: str
    action: str
    running: bool
    speed: float
    extra: Dict[str, Any] = Field(default_factory=dict)


class StatusResponse(BaseModel):
    """Body for GET /api/status."""
    model_config = ConfigDict(extra="forbid")

    status: str
    running: bool
    speed: float
    initialized: bool
    subscribers: int
    sim_step: int
    sim_time_minutes: float
    llm_engine_active: bool
    version: str = "1.0.0"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _coordinator(request: Request) -> SimulationCoordinator:
    coord: Optional[SimulationCoordinator] = getattr(request.app.state, "coordinator", None)
    if coord is None:
        raise HTTPException(status_code=503, detail="Coordinator not attached")
    return coord


# ---------------------------------------------------------------------------
# Endpoint definitions
# ---------------------------------------------------------------------------


@router.post("/chat")
async def chat_endpoint(request: Request, body: ChatRequest) -> StreamingResponse:
    """Translates a natural-language message and streams the response text, then injects constraints."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio
    import os
    import json
    
    async def sse_generator():
        # Only streaming if local Ollama is configured
        ollama_url = os.environ.get("OLLAMA_URL")
        if ollama_url:
            from src.nlp.local_translator import LocalTranslator, build_full_prompt
            ollama_model = os.environ.get("OLLAMA_MODEL", "qwen3:1.7b")
            ollama_timeout = float(os.environ.get("OLLAMA_TIMEOUT_SECONDS", "180.0"))
            
            local_t = LocalTranslator(
                backend_type="ollama", 
                ollama_url=ollama_url, 
                model_name=ollama_model,
                timeout=ollama_timeout
            )
            
            prompt = build_full_prompt(body.message)
            full_text = ""
            ui_text_sent = False
            is_json_part = False
            
            # Stream the conversational response
            for chunk in local_t.backend.generate_stream(prompt=prompt, grammar=None):
                full_text += chunk
                
                # Check if we hit the JSON block
                if "JSON:" in full_text or "{" in full_text:
                    if not is_json_part:
                        is_json_part = True
                        # Send whatever text was before the JSON marker just in case
                        idx = full_text.find("JSON:")
                        if idx == -1: idx = full_text.find("{")
                        if idx > 0:
                            clean_text = full_text[:idx].replace("Response:", "").strip()
                            if clean_text and not ui_text_sent:
                                yield f"data: {json.dumps({'chunk': clean_text})}\n\n"
                                ui_text_sent = True
                else:
                    # Filter out the "Response:" prefix
                    clean_chunk = chunk
                    if "Response:" in full_text and not ui_text_sent:
                        clean_chunk = full_text.replace("Response:", "").lstrip()
                        ui_text_sent = True
                        yield f"data: {json.dumps({'chunk': clean_chunk})}\n\n"
                    elif ui_text_sent and not is_json_part:
                        yield f"data: {json.dumps({'chunk': clean_chunk})}\n\n"
                
                await asyncio.sleep(0)
            
            # Now parse the full_text for JSON
            res = local_t.parse_raw_output(full_text, original_text=body.message)
            
            # Create a mock TranslationResult to map
            from src.nlp.local_translator import TranslationResult
            local_res = TranslationResult(
                success=True,
                event=res,
                error_message=None,
                raw_response=full_text,
                backend_used="ollama",
                execution_time_ms=0.0
            )
            
            # Map it using same logic from translator.py
            from src.nlp.schemas import ComfortEvent as SemanticComfortEvent
            from src.nlp.schemas import ComfortIntent, SuspectedCause, SeverityLevel, SemanticTranslationResult
            from src.nlp.schemas import ALLOWED_ZONE_IDS, ZONE_ALIAS_MAP
            
            sensation_map = {
                "too_cold": ComfortIntent.TOO_COLD,
                "too_warm": ComfortIntent.TOO_WARM,
                "too_humid": ComfortIntent.TOO_HUMID,
                "too_dry": ComfortIntent.TOO_DRY,
                "stuffy": ComfortIntent.STUFFY,
                "drafty": ComfortIntent.DRAFTY,
                "glare": ComfortIntent.UNKNOWN,
                "other": ComfortIntent.UNKNOWN
            }
            intent = sensation_map.get(res.sensation.lower(), ComfortIntent.UNKNOWN)
            raw_zone = res.location or "open_office"
            norm_zone = str(raw_zone).strip().lower().replace("-", "_").replace(" ", "_")
            zone_id = ZONE_ALIAS_MAP.get(norm_zone, norm_zone)
            if zone_id not in ALLOWED_ZONE_IDS:
                zone_id = "open_office"

            severity = SeverityLevel.MEDIUM
            if res.intensity >= 4:
                severity = SeverityLevel.HIGH
            elif res.intensity <= 2:
                severity = SeverityLevel.LOW

            mapped_event = SemanticComfortEvent(
                event_id=res.event_id,
                zone_id=zone_id,
                intent=intent,
                suspected_cause=SuspectedCause.UNSPECIFIED,
                severity=severity,
                confidence=res.confidence,
                duration_minutes=60,
                source="Ollama",
                reasoning=f"Mapped from local backend. Sensation: {res.sensation}"
            )
            
            # Get the response text part from full_text
            import re
            resp_match = re.search(r"Response:\s*(.*?)(?:\nJSON:|$)", full_text, re.DOTALL)
            friendly_response = resp_match.group(1).strip() if resp_match else "I have updated the system with your feedback."
            
            final_translation = SemanticTranslationResult(
                raw_query=body.message,
                is_applicable=(res.domain.lower() == "thermal"),
                response_text=friendly_response,
                events=[mapped_event],
                timestamp=0.0
            )
            
            # Inject into simulator
            applied = False
            if final_translation.is_applicable and final_translation.events:
                applied = await asyncio.to_thread(coord.inject_semantic_event, final_translation.events[0])
            
            # Yield the final payload
            yield f"data: {json.dumps({'applied': bool(applied), 'is_applicable': final_translation.is_applicable, 'translation': final_translation.model_dump()})}\n\n"
        else:
            # Fallback to sync for cloud LLM
            translation, applied = await _submit_chat(coord, body.message, body.history)
            yield f"data: {json.dumps({'chunk': translation.response_text})}\n\n"
            yield f"data: {json.dumps({'applied': bool(applied), 'is_applicable': bool(translation.is_applicable), 'translation': translation.model_dump()})}\n\n"

    return StreamingResponse(sse_generator(), media_type="text/event-stream")

async def _submit_chat(coord: SimulationCoordinator, message: str, history: List[Dict[str, str]]):
    """Offload the synchronous NLP pipeline to a thread so the loop stays non-blocking."""
    import asyncio

    return await asyncio.to_thread(coord.submit_chat_message, message, history)


@router.get("/zones", response_model=ZonesResponse)
async def zones_endpoint(request: Request) -> ZonesResponse:
    """Returns the current state of all zones."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    zone_states = await asyncio.to_thread(coord.get_zone_states)
    zone_ids = await asyncio.to_thread(coord.get_zone_ids)

    states: Dict[str, ZoneState] = {}
    for zid, st in zone_states.items():
        try:
            states[zid] = ZoneState(**st)
        except Exception:
            # Defensive normalization if upstream sends malformed data.
            states[zid] = ZoneState(
                zone_id=zid,
                temperature_c=float(st.get("temperature_c", 22.0)),
                target_setpoint_c=float(st.get("target_setpoint_c", 22.0)),
                humidity_pct=float(st.get("humidity_pct", 50.0)),
                occupancy_count=int(st.get("occupancy_count", 0)),
                hvac_power_kw=float(st.get("hvac_power_kw", 0.0)),
                comfort_violation_c=float(st.get("comfort_violation_c", 0.0)),
                active_nlp_offset_c=float(st.get("active_nlp_offset_c", 0.0)),
            )

    return ZonesResponse(zones=zone_ids, states=states)


@router.get("/metrics", response_model=MetricsResponse)
async def metrics_endpoint(request: Request, limit: int = 100) -> MetricsResponse:
    """Returns the latest metrics snapshot plus a short history window."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    snap = await asyncio.to_thread(coord.get_metrics_snapshot)
    history_models = await asyncio.to_thread(coord.get_telemetry_history, limit)
    history_dicts = [t.model_dump() for t in history_models]

    if not snap:
        raise HTTPException(status_code=503, detail="No telemetry available yet")

    return MetricsResponse(
        step=int(snap.get("step", 0)),
        timestamp_sim_hour=float(snap.get("timestamp_sim_hour", 0.0)),
        outdoor_temp_c=float(snap.get("outdoor_temp_c", 0.0)),
        outdoor_humidity_pct=float(snap.get("outdoor_humidity_pct", 0.0)),
        solar_irradiance_w_m2=float(snap.get("solar_irradiance_w_m2", 0.0)),
        electricity_price_usd_kwh=float(snap.get("electricity_price_usd_kwh", 0.0)),
        baseline_power_kw=float(snap.get("baseline_power_kw", 0.0)),
        rl_power_kw=float(snap.get("rl_power_kw", 0.0)),
        power_saved_kw=float(snap.get("power_saved_kw", 0.0)),
        instantaneous_savings_pct=float(snap.get("instantaneous_savings_pct", 0.0)),
        cumulative_baseline_energy_kwh=float(snap.get("cumulative_baseline_energy_kwh", 0.0)),
        cumulative_rl_energy_kwh=float(snap.get("cumulative_rl_energy_kwh", 0.0)),
        cumulative_savings_pct=float(snap.get("cumulative_savings_pct", 0.0)),
        cumulative_cost_saved_usd=float(snap.get("cumulative_cost_saved_usd", 0.0)),
        baseline_comfort_violation_total=float(snap.get("baseline_comfort_violation_total", 0.0)),
        rl_comfort_violation_total=float(snap.get("rl_comfort_violation_total", 0.0)),
        history=history_dicts,
    )


@router.post("/simulation/control", response_model=SimulationControlResponse)
async def simulation_control_endpoint(
    request: Request, body: SimulationControlRequest
) -> SimulationControlResponse:
    """Handles start/pause/step/reset/set_speed/set_weather_preset commands."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    action = body.action
    extra: Dict[str, Any] = {}

    if action == "start":
        if body.speed is not None:
            await asyncio.to_thread(coord.set_speed, body.speed)
        await asyncio.to_thread(coord.start)
    elif action == "pause":
        await asyncio.to_thread(coord.pause)
    elif action == "reset":
        await asyncio.to_thread(coord.reset)
    elif action == "step":
        steps = int(body.steps or 1)
        latest = await asyncio.to_thread(coord.step, steps)
        if latest is not None:
            extra["step_executed"] = int(latest.step)
    elif action == "set_speed":
        if body.speed is None:
            raise HTTPException(status_code=422, detail="speed is required for set_speed")
        new_speed = await asyncio.to_thread(coord.set_speed, body.speed)
        extra["new_speed"] = float(new_speed)
    elif action == "set_weather_preset":
        if body.preset is None:
            raise HTTPException(status_code=422, detail="preset is required for set_weather_preset")
        try:
            preset_enum = WeatherPreset(body.preset)
        except ValueError as exc:
            raise HTTPException(
                status_code=422,
                detail=f"unknown preset '{body.preset}'",
            ) from exc
        # Apply preset: simplest path is to swap the underlying generator's preset.
        await asyncio.to_thread(_apply_preset, coord, preset_enum)
        extra["preset"] = preset_enum.value

    return SimulationControlResponse(
        status="success",
        action=action,
        running=coord.is_running(),
        speed=coord.get_speed(),
        extra=extra,
    )


def _apply_preset(coord: SimulationCoordinator, preset: WeatherPreset) -> None:
    """Re-initializes the runner's weather generator with a new preset."""
    runner = coord.runner
    runner.env.weather_gen.reset(preset=preset)
    runner.weather_preset = preset
    # The runner's own weather_preset is informational; the env's weather_gen drives everything.


@router.get("/status", response_model=StatusResponse)
async def status_endpoint(request: Request) -> StatusResponse:
    """Returns current system status (health, running flag, sim tick, etc.)."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    import asyncio

    sim_minutes = await asyncio.to_thread(coord.get_current_sim_time_minutes)
    return StatusResponse(
        status="healthy",
        running=coord.is_running(),
        speed=coord.get_speed(),
        initialized=coord.is_initialized(),
        subscribers=coord.get_subscriber_count(),
        sim_step=int(sim_minutes / 5.0),
        sim_time_minutes=float(sim_minutes),
        llm_engine_active=bool(getattr(coord, "_llm_engine_active", False)),
    )


@router.get("/stream")
async def stream_endpoint(request: Request) -> StreamingResponse:
    """Server-Sent Events telemetry stream."""
    coord = _coordinator(request)
    if not coord.is_initialized():
        coord.initialize()

    generator = telemetry_event_stream(coord)
    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",  # disable nginx buffering
            "Content-Type": "text/event-stream",
        },
    )


__all__ = [
    "router",
    "ChatRequest",
    "ChatResponse",
    "ZoneState",
    "ZonesResponse",
    "MetricsResponse",
    "SimulationControlRequest",
    "SimulationControlResponse",
    "StatusResponse",
]
